(SELECT ANIMAL_ID, NAME, 'O' AS 중성화 FROM ANIMAL_INS WHERE SEX_UPON_INTAKE LIKE 'Neutered%' OR SEX_UPON_INTAKE LIKE 'Spayed%')
UNION
(SELECT ANIMAL_ID, NAME, 'X' AS 중성화 FROM ANIMAL_INS WHERE SEX_UPON_INTAKE LIKE 'Intact%')
ORDER BY ANIMAL_ID;

